version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    container_name: tutoring_app_dev
    volumes:
      - .:/var/www/html
    depends_on:
      - database
      - redis
    networks:
      - tutoring_network

  nginx:
    image: nginx:alpine
    container_name: tutoring_nginx_dev
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - tutoring_network

  database:
    image: mysql:8.0
    container_name: tutoring_db_dev
    environment:
      MYSQL_DATABASE: tutoring_platform
      MYSQL_USER: tutoring_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tutoring_network

  redis:
    image: redis:7-alpine
    container_name: tutoring_redis_dev
    ports:
      - "6379:6379"
    networks:
      - tutoring_network

  vite:
    image: node:18-alpine
    container_name: tutoring_vite_dev
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - tutoring_network

volumes:
  mysql_data:

networks:
  tutoring_network:
    driver: bridge
